### ISSUE TITLE
Requests is blocking code.

### ISSUE THREAD

**Issue by laggycomputer** [GiacomoLaw/discordbot#1]
I'd like to point out that you are using `requests` for commands. It's a good library but sadly is non-asynchronous. Your web requests jam up the bot thread, and can cause Discord to disconnect you in some cases.

`aiohttp` is the best option here, setting a botvar to a `ClientSession`.

I'd be glad to PR this, just giving others a chance to give input.

**Comment by GiacomoLaw** [comment]
Thanks. Pretty new to discord.py so have no idea what I’m doing. A PR would be great!
