### ISSUE TITLE
Outdated code.

### ISSUE THREAD

**Issue by laggycomputer** [GiacomoLaw/discordbot#2]
This project is now outdated, as the `rewrite` branch of `discord.py` was just merged into `master`.

The version of the library now on PyPi includes some major breaking changes.

As with #1, I'd be glad to PR this.

P.S the docs on migration are available at https://discordpy.readthedocs.io/en/latest/migrating.html

**Comment by laggycomputer** [comment]
On this topic, custom help commands were made easier to create with the "rewrite release". You can implement better-looking help commands easily, without hard-coding dialog (as is currently being done).
See the docs at https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#help-commands

**Comment by GiacomoLaw** [comment]
If you could pr something that would be great. I’ve just kind of thrown it together as I don’t have a server to run it on anyway.

**Comment by laggycomputer** [comment]
Where to host? If there is a PC in the house that is up at least 12 hours a day, it can host the but just fine.
If you have a laptop that you leave at home frequently, you can use that as well.
If you need very few hosting hours, you can use Heroku, sacrificing control of your application, runtime (you have limited hours per month), voice support (and anything else w/ C bindings), and more.

Of course, there are always friends, if you're lucky...

**Comment by GiacomoLaw** [comment]
Using Heroku, thanks!

**Comment by GiacomoLaw** [comment]
@laggycomputer Any update on this? I tried to do it myself but messed it all up 😬 

Thanks!

**Comment by laggycomputer** [comment]
So sorry for failing to respond. I will try to create a PR for this soon™.

**Comment by GiacomoLaw** [comment]
No worries at all, thanks!
